### ISSUE TITLE
Peer to peer Code Review

### ISSUE THREAD

**Issue by Luiscarlosvd** [JuanDiegoGuerra/Leaderboard#4]
Hi @JuanDiegoGuerra!

You have done an excellent job and your code is looking good! 😃 

- Your code is clean and organized!
- The JavaScript file looks really nice, It's very compressed and easy to understand, congrats! 🥂 

Keep it up and Happy coding!! 🎉🍾

**Comment by romans-adi** [comment]
Apologies for the delay, but I discovered an area in your HTML document that could be improved : 

- Kindly suggest enhancing accessibility by adding the `aria-label` attribute to each line of your `input` field

https://github.com/JuanDiegoGuerra/Leaderboard/blob/07b08ce464f46a1f72ec86b84e941851870632ec/src/index.html#L26

https://github.com/JuanDiegoGuerra/Leaderboard/blob/07b08ce464f46a1f72ec86b84e941851870632ec/src/index.html#L28

I admire your coding style and the way you implement the functionality. Keep up the great work and enjoy coding! :partying_face: :robot:
